version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - DB_HOST=db
      - DB_PORT=5432



  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    build: ./main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - DB_NAME=main
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - DB_HOST=db
      - DB_PORT=5432

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
